//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiyaJuwarkarProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKEXPERIENCE
    {
        public int ID { get; set; }
        public int CANDIDATEID { get; set; }
        public string EMPLOYER { get; set; }
        public Nullable<System.DateTime> FROMDATE { get; set; }
        public Nullable<System.DateTime> TODATE { get; set; }
    
        public virtual CANDIDATE CANDIDATE { get; set; }
    }
}
